name = "ralph-island-game"
main = "src/index.ts"
compatibility_date = "2025-11-01"

routes = [
  { pattern = "will.ralph-island.com", custom_domain = true }
]

[assets]
directory = "../dist"
binding = "ASSETS"

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "RoomDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDurableObject"]
